apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: redis
        resources: {}

        volumeMounts:
        - name: redis-hc
          mountPath: "/usr/local/bin/redis_healthcheck.sh"
          subPath: "redis_healthcheck.sh"
          readOnly: false

      initContainers:
      - name: init-redis-hc
        image: alpine:latest
        command: ["chmod", "a+x", "/usr/local/bin/redis_healthcheck.sh"]

        volumeMounts:
        - name: redis-hc
          mountPath: "/usr/local/bin/redis_healthcheck.sh"
          subPath: "redis_healthcheck.sh"
          readOnly: false

      volumes:
      - name: redis-hc
        configMap:
          name: redis-hc-cm
status: {}
