apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-lb
  name: nginx-lb
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-lb
  type: LoadBalancer
status:
  loadBalancer: {}
