apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wp-db-cip
  name: wp-db-cip
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wp-db-deploy
  type: ClusterIP
status:
  loadBalancer: {}
