apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wp-lb
  name: wp-lb
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-app-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
