apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: php
    spec:
      containers:
      - image: php:8.2.27-apache
        name: php
        resources: {}
status: {}
