apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-deploy
  name: wordpress-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress-deploy
    spec:
      containers:
      - image: wordpress
        name: wordpress
        resources: {}
        volumeMounts:
          - mountPath: /var/www/html
            name: wordpress-data
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc
status: {}
