apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-deploy
  name: mariadb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb-deploy
    spec:
      volumes:
      - name: mariadb-vol
        hostPath:
          path: /Users/bjornsonnen/Documents/Open-Source/lab/Kubernetes/apps/nextcloud/mariadb
      containers:
      - image: mariadb
        name: mariadb
        resources: {}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Password123!
        - name: MYSQL_DATABASE
          value: nextcloud
        volumeMounts:
        - name: mariadb-vol
          mountPath: /var/lib/mysql
status: {}
