apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nextcloud-lb
  name: nextcloud-lb
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nextcloud-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
