apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nextcloud-deploy
  name: nextcloud-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nextcloud-deploy
    spec:
      volumes:
      - name: nextcloud-vol
        hostPath:
          path: /Users/bjornsonnen/Documents/Open-Source/lab/Kubernetes/apps/nextcloud/nextcloud
      containers:
      - image: nextcloud
        name: nextcloud
        resources: {}
        volumeMounts:
        - name: nextcloud-vol
          mountPath: /var/www/html
status: {}
