apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: http-deploy-replicas
  name: http-deploy-replicas
spec:
  replicas: 20
  selector:
    matchLabels:
      app: http-deploy-replicas
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: http-deploy-replicas
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
